import '../config/api_config.dart';

class AppConstants {
  static const String apiKey = ApiConfig.footballApiKey;

  // League IDs mapping - Organized by priority and importance
  static const Map<String, int> leagueIds = {
    // Major European Leagues (Top 5)
    'Premier League': 39,
    'La Liga': 140,
    'Bundesliga': 78,
    'Serie A': 135,
    'Ligue 1': 61,

    // Other European Top Leagues
    'Eredivisie': 88,
    'Primeira Liga': 94,
    'Championship': 40,
    'Scottish Premiership': 39,
    'Belgian Pro League': 144,

    'Polish Ekstraklasa': 106,
    'Austrian Bundesliga': 218,
    'Swiss Super League': 207,
    'Danish Superliga': 119,

    'Greek Super League': 197,
    'Czech First League': 319,
    'Hungarian NB I': 218,
    'Romanian Liga I': 203,
    'Bulgarian First League': 103,
    'Croatian First League': 203,
    'Serbian Super Liga': 197,
    'Slovenian PrvaLiga': 197,
    'Slovak Super Liga': 197,

    // European Competitions
    'UEFA Champions League': 2,
    'UEFA Europa League': 3,
    'UEFA Conference League': 848,
    'UEFA Europa Conference League': 848,

    // International Competitions
    'FIFA World Cup': 1,
    'FIFA Club World Cup': 15,
    'UEFA European Championship': 4,
    'Copa América': 9,
    'AFC Asian Cup': 15,
    'CAF Africa Cup of Nations': 13,
    'CONCACAF Gold Cup': 22,
    'OFC Nations Cup': 14,

    // Continental Club Competitions
    'AFC Champions League': 7,
    'CAF Champions League': 5,
    'CONCACAF Champions League': 6,
    'Copa Libertadores': 10,
    'Copa Sudamericana': 11,

    // Additional International Competitions
    'UEFA Super Cup': 4,
    'Recopa Sudamericana': 12,
    'Taça de Portugal': 14,
    'New Zealand Football Championship': 15,
    'A-League': 16,

    // Additional National Competitions
    'Copa del Rey': 143,
    'FA Cup': 171,
    'DFB Pokal': 81,
    'Coppa Italia': 137,
    'Coupe de France': 66,
    'Türkiye Kupası': 203,
    'Copa Argentina': 87,
    'Copa Chile': 218,
    'Copa Colombia': 239,
    'Copa do Brasil': 71,
    'Copa MX': 263,
    'US Open Cup': 257,

    // Arab Leagues (Organized by region)
    // Gulf Region
    'Saudi Pro League': 207,
    'UAE Pro League': 111,
    'Qatar Stars League': 119,
    'Kuwait Premier League': 729,
    'Bahraini Premier League': 728,
    'Oman Professional League': 727,

    // North Africa
    'Egyptian Premier League': 65,
    'Moroccan Botola': 66,
    'Tunisian Ligue 1': 68,
    'Algerian Ligue 1': 67,
    'Libyan Premier League': 730,
    'Sudan Premier League': 726,

    // Levant Region
    'Syrian Premier League': 719,
    'Jordanian Pro League': 724,
    'Lebanese Premier League': 725,
    'Palestinian Premier League': 731,
    'Iraqi Premier League': 207,
    'Yemeni League': 732,

    // Regional Arab Tournaments
    'Arab Club Champions Cup': 844,
    'GCC Champions League': 845,
    'North African Cup': 846,
    'Arab Cup': 847,

    // Major South American Leagues
    'Brazilian Serie A': 71,
    'Argentine Primera División': 87,
    'Colombian Primera A': 239,
    'Chilean Primera División': 218,
    'Peruvian Primera División': 203,
    'Uruguayan Primera División': 203,
    'Paraguayan Primera División': 203,
    'Ecuadorian Serie A': 203,
    'Venezuelan Primera División': 203,
    'Bolivian Primera División': 203,

    // Major Asian Leagues
    'Chinese Super League': 169,
    'South Korean K League 1': 292,
    'Australian A-League': 1,
    'Indian Super League': 322,
    'Thai League 1': 302,
    'Vietnamese V.League 1': 302,
    'Indonesian Liga 1': 302,
    'Malaysian Super League': 302,
    'Singapore Premier League': 302,

    // Major African Leagues
    'South African Premier Division': 1,
    'Nigerian Professional Football League': 1,
    'Ghanaian Premier League': 1,
    'Kenyan Premier League': 1,
    'Tanzanian Premier League': 1,
    'Ugandan Premier League': 1,
    'Zambian Super League': 1,
    'Zimbabwean Premier Soccer League': 1,
    'Botswana Premier League': 1,
    'Namibian Premier League': 1,
  };

  // Club IDs mapping - Major clubs from around the world
  static const Map<String, int> clubIds = {
    // English Premier League
    'Manchester City': 50,
    'Liverpool': 40,
    'Arsenal': 42,
    'Manchester United': 33,
    'Chelsea': 49,
    'Tottenham Hotspur': 47,
    'Newcastle United': 34,
    'Aston Villa': 66,
    'Brighton & Hove Albion': 51,
    'West Ham United': 48,
    'Brentford': 55,
    'Fulham': 36,
    'Crystal Palace': 52,
    'Wolverhampton Wanderers': 39,
    'Nottingham Forest': 65,
    'Everton': 45,
    'Leicester City': 46,
    'Leeds United': 63,
    'Southampton': 41,
    'Bournemouth': 35,

    // Spanish La Liga
    'Real Madrid': 541,
    'Barcelona': 529,
    'Atlético Madrid': 530,
    'Sevilla': 536,
    'Real Sociedad': 548,
    'Villarreal': 533,
    'Athletic Bilbao': 531,
    'Real Betis': 150,
    'Valencia': 532,
    'Girona': 745,
    'Getafe': 82,
    'Rayo Vallecano': 80,
    'Osasuna': 79,
    'Celta Vigo': 558,
    'Mallorca': 798,
    'Alavés': 263,
    'Las Palmas': 275,
    'Granada': 95,
    'Cádiz': 724,
    'Almería': 723,

    // German Bundesliga
    'Bayern Munich': 157,
    'Borussia Dortmund': 165,
    'RB Leipzig': 173,
    'Bayer Leverkusen': 161,
    'VfB Stuttgart': 172,
    'Eintracht Frankfurt': 169,
    'TSG Hoffenheim': 167,
    'SC Freiburg': 160,
    'VfL Wolfsburg': 161,
    '1. FC Heidenheim': 180,
    '1. FC Union Berlin': 182,
    'SV Darmstadt 98': 181,
    'FC Augsburg': 170,
    'Borussia Mönchengladbach': 159,
    '1. FC Köln': 1,
    'Werder Bremen': 162,
    'FSV Mainz 05': 164,
    'VfL Bochum': 80,

    // Italian Serie A
    'Inter Milan': 505,
    'AC Milan': 489,
    'Juventus': 496,
    'Napoli': 492,
    'Atalanta': 499,
    'Roma': 497,
    'Lazio': 487,
    'Fiorentina': 502,
    'Bologna': 500,
    'Torino': 503,
    'Genoa': 495,
    'Monza': 1579,
    'Lecce': 867,
    'Sassuolo': 488,
    'Frosinone': 2954,
    'Cagliari': 490,
    'Udinese': 494,
    'Empoli': 511,
    'Salernitana': 514,
    'Verona': 504,

    // French Ligue 1
    'PSG': 85,
    'Monaco': 91,
    'Lens': 116,
    'Marseille': 81,
    'Lyon': 80,
    'Lille': 79,
    'Reims': 93,
    'Nice': 84,
    'Strasbourg': 77,
    'Nantes': 95,
    'Toulouse': 96,
    'Brest': 94,
    'Le Havre': 111,
    'Metz': 112,
    'Clermont Foot': 99,
    'Montpellier': 82,
    'Rennes': 80,
    'Lorient': 97,

    // Arab Clubs
    'Al Hilal (KSA)': 2802,
    'Al Hilal': 2802,
    'Al Nassr (KSA)': 2803,
    'Al Nassr': 2803,
    'Al Ahly (EGY)': 1,
    'Al Ahly': 1,
    'Zamalek (EGY)': 2,
    'Zamalek': 2,
    'Al Ain (UAE)': 3,
    'Al Ain': 3,
    'Al Sadd (QAT)': 4,
    'Al Sadd': 4,
    'Raja Casablanca (MAR)': 5,
    'Raja Casablanca': 5,
    'Wydad Casablanca (MAR)': 6,
    'Wydad Casablanca': 6,
    'Espérance de Tunis (TUN)': 7,
    'Espérance de Tunis': 7,
    'Club Africain (TUN)': 8,
    'Club Africain': 8,
    'Al Ittihad (KSA)': 2804,
    'Al Ittihad': 2804,
    'Al Shabab (KSA)': 2805,
    'Al Shabab': 2805,
    'Al Wahda (UAE)': 2806,
    'Al Wahda': 2806,
    'Al Wasl (UAE)': 2807,
    'Al Wasl': 2807,
    'Al Jazira (UAE)': 2808,
    'Al Jazira': 2808,
    'Al Rayyan (QAT)': 2810,
    'Al Rayyan': 2810,
    'Al Duhail (QAT)': 2811,
    'Al Duhail': 2811,
    'Al Gharafa (QAT)': 2812,
    'Al Gharafa': 2812,
    'Al Wakrah (QAT)': 2813,
    'Al Wakrah': 2813,
    'Al Khor (QAT)': 2814,
    'Al Khor': 2814,
    'Al Sailiya (QAT)': 2815,
    'Al Sailiya': 2815,
    'Al Markhiya (QAT)': 2816,
    'Al Markhiya': 2816,
    'Al Shamal (QAT)': 2817,
    'Al Shamal': 2817,
    'Al Fateh (KSA)': 2819,
    'Al Fateh': 2819,
    'Al Taawoun (KSA)': 2820,
    'Al Taawoun': 2820,
    'Al Faisaly (KSA)': 2821,
    'Al Faisaly': 2821,
    'Al Raed (KSA)': 2822,
    'Al Raed': 2822,
    'Al Batin (KSA)': 2823,
    'Al Batin': 2823,
    'Al Adalah (KSA)': 2824,
    'Al Adalah': 2824,
    'Al Hazm (KSA)': 2825,
    'Al Hazm': 2825,
    'Al Okhdood (KSA)': 2826,
    'Al Okhdood': 2826,
    'Al Riyadh (KSA)': 2843,
    'Al Riyadh': 2843,
    'Al Ettifaq (KSA)': 2844,
    'Al Ettifaq': 2844,
    'Al Khaleej (KSA)': 2845,
    'Al Khaleej': 2845,
  };

  // Championships in Arabic - Organized by region and importance
  static const Map<String, String> championshipsArabic = {
    // Major European Leagues
    'Premier League': 'الدوري الإنجليزي الممتاز',
    'La Liga': 'الدوري الإسباني',
    'Bundesliga': 'الدوري الألماني',
    'Serie A': 'الدوري الإيطالي',
    'Ligue 1': 'الدوري الفرنسي',

    // Other European Leagues
    'Eredivisie': 'الدوري الهولندي',
    'Primeira Liga': 'الدوري البرتغالي',
    'Championship': 'دوري البطولة الإنجليزية',
    'Scottish Premiership': 'الدوري الإسكتلندي الممتاز',
    'Belgian Pro League': 'الدوري البلجيكي للمحترفين',
    'Turkish Süper Lig': 'الدوري التركي الممتاز',
    'Russian Premier League': 'الدوري الروسي الممتاز',
    'Ukrainian Premier League': 'الدوري الأوكراني الممتاز',
    'Polish Ekstraklasa': 'الدوري البولندي',
    'Austrian Bundesliga': 'الدوري النمساوي',
    'Swiss Super League': 'الدوري السويسري الممتاز',
    'Danish Superliga': 'الدوري الدنماركي الممتاز',
    'Norwegian Eliteserien': 'الدوري النرويجي الممتاز',
    'Swedish Allsvenskan': 'الدوري السويدي الممتاز',
    'Finnish Veikkausliiga': 'الدوري الفنلندي',
    'Greek Super League': 'الدوري اليوناني الممتاز',
    'Czech First League': 'الدوري التشيكي الأول',
    'Hungarian NB I': 'الدوري المجري الأول',
    'Romanian Liga I': 'الدوري الروماني الأول',
    'Bulgarian First League': 'الدوري البلغاري الأول',
    'Croatian First League': 'الدوري الكرواتي الأول',
    'Serbian Super Liga': 'الدوري الصربي الممتاز',
    'Slovenian PrvaLiga': 'الدوري السلوفيني الأول',
    'Slovak Super Liga': 'الدوري السلوفاكي الممتاز',

    // European Competitions
    'UEFA Champions League': 'دوري أبطال أوروبا',
    'UEFA Europa League': 'الدوري الأوروبي',
    'UEFA Conference League': 'دوري المؤتمر الأوروبي',
    'UEFA Europa Conference League': 'دوري المؤتمر الأوروبي',

    // International Competitions
    'FIFA World Cup': 'كأس العالم',
    'FIFA Club World Cup': 'كأس العالم للأندية',
    'UEFA European Championship': 'البطولة الأوروبية',
    'Copa América': 'كوبا أمريكا',
    'AFC Asian Cup': 'كأس آسيا',
    'CAF Africa Cup of Nations': 'كأس الأمم الأفريقية',
    'CONCACAF Gold Cup': 'كأس الكونكاكاف الذهبي',
    'OFC Nations Cup': 'كأس أوقيانوسيا',

    // Continental Club Competitions
    'AFC Champions League': 'دوري أبطال آسيا',
    'CAF Champions League': 'دوري أبطال أفريقيا',
    'CONCACAF Champions League': 'دوري أبطال الكونكاكاف',
    'Copa Libertadores': 'كوبا ليبرتادوريس',
    'Copa Sudamericana': 'كوبا سود أمريكانا',

    // Additional International Competitions
    'UEFA Super Cup': 'كأس السوبر الأوروبي',
    'Recopa Sudamericana': 'كأس ريكوبا سود أمريكانا',
    'Taça de Portugal': 'كأس البرتغال',
    'New Zealand Football Championship': 'دوري نيوزيلندا الممتاز',
    'A-League': 'الدوري الأسترالي الممتاز',

    // Additional National Competitions
    'Copa del Rey': 'كأس الملك',
    'FA Cup': 'كأس الاتحاد الإنجليزي',
    'DFB Pokal': 'كأس ألمانيا',
    'Coppa Italia': 'كأس إيطاليا',
    'Coupe de France': 'كأس فرنسا',
    'Türkiye Kupası': 'كأس تركيا',
    'Copa Argentina': 'كأس الأرجنتين',
    'Copa Chile': 'كأس تشيلي',
    'Copa Colombia': 'كأس كولومبيا',
    'Copa do Brasil': 'كأس البرازيل',
    'Copa MX': 'كأس المكسيك',
    'US Open Cup': 'كأس الولايات المتحدة المفتوح',

    // Arab Leagues - Gulf Region
    'Saudi Pro League': 'الدوري السعودي للمحترفين',
    'UAE Pro League': 'دوري الخليج العربي',
    'Qatar Stars League': 'دوري نجوم قطر',
    'Kuwait Premier League': 'الدوري الكويتي الممتاز',
    'Bahraini Premier League': 'الدوري البحريني الممتاز',
    'Oman Professional League': 'الدوري العماني للمحترفين',

    // Arab Leagues - North Africa
    'Egyptian Premier League': 'الدوري المصري الممتاز',
    'Moroccan Botola': 'البطولة المغربية',
    'Tunisian Ligue 1': 'الدوري التونسي الأول',
    'Algerian Ligue 1': 'الدوري الجزائري الأول',
    'Libyan Premier League': 'الدوري الليبي الممتاز',
    'Sudan Premier League': 'الدوري السوداني الممتاز',

    // Arab Leagues - Levant Region
    'Syrian Premier League': 'الدوري السوري الممتاز',
    'Jordanian Pro League': 'الدوري الأردني للمحترفين',
    'Lebanese Premier League': 'الدوري اللبناني الممتاز',
    'Palestinian Premier League': 'الدوري الفلسطيني الممتاز',
    'Iraqi Premier League': 'الدوري العراقي الممتاز',
    'Yemeni League': 'الدوري اليمني',

    // Regional Arab Tournaments
    'Arab Club Champions Cup': 'كأس الملك سلمان للأندية',
    'GCC Champions League': 'دوري أبطال الخليج',
    'North African Cup': 'كأس شمال أفريقيا',
    'Arab Cup': 'كأس العرب',

    // Major South American Leagues
    'Brazilian Serie A': 'الدوري البرازيلي الدرجة الأولى',
    'Argentine Primera División': 'الدوري الأرجنتيني الدرجة الأولى',
    'Colombian Primera A': 'الدوري الكولومبي الدرجة الأولى',
    'Chilean Primera División': 'الدوري التشيلي الدرجة الأولى',
    'Peruvian Primera División': 'الدوري البيروفي الدرجة الأولى',
    'Uruguayan Primera División': 'الدوري الأوروغواياني الدرجة الأولى',
    'Paraguayan Primera División': 'الدوري الباراغواياني الدرجة الأولى',
    'Ecuadorian Serie A': 'الدوري الإكوادوري الدرجة الأولى',
    'Venezuelan Primera División': 'الدوري الفنزويلي الدرجة الأولى',
    'Bolivian Primera División': 'الدوري البوليفي الدرجة الأولى',

    // Major Asian Leagues
    'Chinese Super League': 'الدوري الصيني الممتاز',
    'South Korean K League 1': 'الدوري الكوري الجنوبي الدرجة الأولى',
    'Australian A-League': 'الدوري الأسترالي الممتاز',
    'Indian Super League': 'الدوري الهندي الممتاز',
    'Thai League 1': 'الدوري التايلندي الدرجة الأولى',
    'Vietnamese V.League 1': 'الدوري الفيتنامي الدرجة الأولى',
    'Indonesian Liga 1': 'الدوري الإندونيسي الدرجة الأولى',
    'Malaysian Super League': 'الدوري الماليزي الممتاز',
    'Singapore Premier League': 'الدوري السنغافوري الممتاز',

    // Major African Leagues
    'South African Premier Division': 'الدوري الجنوب أفريقي الممتاز',
    'Nigerian Professional Football League': 'الدوري النيجيري للمحترفين',
    'Ghanaian Premier League': 'الدوري الغاني الممتاز',
    'Kenyan Premier League': 'الدوري الكيني الممتاز',
    'Tanzanian Premier League': 'الدوري التنزاني الممتاز',
    'Ugandan Premier League': 'الدوري الأوغندي الممتاز',
    'Zambian Super League': 'الدوري الزامبي الممتاز',
    'Zimbabwean Premier Soccer League': 'الدوري الزيمبابوي الممتاز',
    'Botswana Premier League': 'الدوري البوتسواني الممتاز',
    'Namibian Premier League': 'الدوري الناميبي الممتاز',
  };

  // Clubs in Arabic - Major clubs from around the world
  static const Map<String, String> clubsArabic = {
    // English Premier League
    'Manchester City': 'مانشستر سيتي',
    'Liverpool': 'ليفربول',
    'Arsenal': 'آرسنال',
    'Manchester United': 'مانشستر يونايتد',
    'Chelsea': 'تشيلسي',
    'Tottenham Hotspur': 'توتنهام هوتسبير',
    'Newcastle United': 'نيوكاسل يونايتد',
    'Aston Villa': 'أستون فيلا',
    'Brighton & Hove Albion': 'برايتون أند هوف ألبايون',
    'West Ham United': 'وست هام يونايتد',
    'Brentford': 'برينتفورد',
    'Fulham': 'فولهام',
    'Crystal Palace': 'كريستال بالاس',
    'Wolverhampton Wanderers': 'وولفرهامبتون واندررز',
    'Nottingham Forest': 'نوتنغهام فورست',
    'Everton': 'إيفرتون',
    'Leicester City': 'ليستر سيتي',
    'Leeds United': 'ليدز يونايتد',
    'Southampton': 'ساوثهامبتون',
    'Bournemouth': 'بورنموث',

    // Spanish La Liga
    'Real Madrid': 'ريال مدريد',
    'Barcelona': 'برشلونة',
    'Atlético Madrid': 'أتلتيكو مدريد',
    'Sevilla': 'إشبيلية',
    'Real Sociedad': 'ريال سوسيداد',
    'Villarreal': 'فياريال',
    'Athletic Bilbao': 'أتلتيك بيلباو',
    'Real Betis': 'ريال بيتيس',
    'Valencia': 'فالنسيا',
    'Girona': 'خيرونا',
    'Getafe': 'خيتافي',
    'Rayo Vallecano': 'رايو فاييكانو',
    'Osasuna': 'أوساسونا',
    'Celta Vigo': 'سيلتا فيغو',
    'Mallorca': 'مايوركا',
    'Alavés': 'ألافيس',
    'Las Palmas': 'لاس بالماس',
    'Granada': 'غرناطة',
    'Cádiz': 'قادس',
    'Almería': 'ألميريا',

    // German Bundesliga
    'Bayern Munich': 'بايرن ميونخ',
    'Borussia Dortmund': 'بوروسيا دورتموند',
    'RB Leipzig': 'آر بي لايبزيغ',
    'Bayer Leverkusen': 'باير ليفركوزن',
    'VfB Stuttgart': 'شتوتغارت',
    'Eintracht Frankfurt': 'آينتراخت فرانكفورت',
    'TSG Hoffenheim': 'هوفنهايم',
    'SC Freiburg': 'فرايبورغ',
    'VfL Wolfsburg': 'فولفسبورغ',
    '1. FC Heidenheim': 'هايدنهايم',
    '1. FC Union Berlin': 'يونيون برلين',
    'SV Darmstadt 98': 'دارمشتات',
    'FC Augsburg': 'آوغسبورغ',
    'Borussia Mönchengladbach': 'بوروسيا مونشنغلادباخ',
    '1. FC Köln': 'كولن',
    'Werder Bremen': 'فيردر بريمن',
    'FSV Mainz 05': 'ماينتس',
    'VfL Bochum': 'بوخوم',

    // Italian Serie A
    'Inter Milan': 'إنتر ميلان',
    'AC Milan': 'إيه سي ميلان',
    'Juventus': 'يوفنتوس',
    'Napoli': 'نابولي',
    'Atalanta': 'أتالانتا',
    'Roma': 'روما',
    'Lazio': 'لاتسيو',
    'Fiorentina': 'فيورنتينا',
    'Bologna': 'بولونيا',
    'Torino': 'تورينو',
    'Genoa': 'جنوة',
    'Monza': 'مونتزا',
    'Lecce': 'ليتشي',
    'Sassuolo': 'ساسولو',
    'Frosinone': 'فروزينوني',
    'Cagliari': 'كالياري',
    'Udinese': 'أودينيزي',
    'Empoli': 'إمبولي',
    'Salernitana': 'ساليرنيتانا',
    'Verona': 'فيرونا',

    // French Ligue 1
    'PSG': 'باريس سان جيرمان',
    'Monaco': 'موناكو',
    'Lens': 'لانس',
    'Marseille': 'مرسيليا',
    'Lyon': 'ليون',
    'Lille': 'ليل',
    'Reims': 'رانس',
    'Nice': 'نيس',
    'Strasbourg': 'ستراسبورغ',
    'Nantes': 'نانت',
    'Toulouse': 'تولوز',
    'Brest': 'بريست',
    'Le Havre': 'لو هافر',
    'Metz': 'متز',
    'Clermont Foot': 'كليرمونت',
    'Montpellier': 'مونبلييه',
    'Rennes': 'رين',
    'Lorient': 'لوريان',

    // Arab Clubs
    'Al Hilal (KSA)': 'الهلال',
    'Al Hilal': 'الهلال',
    'Al Nassr (KSA)': 'النصر',
    'Al Nassr': 'النصر',
    'Al Ahly (EGY)': 'الأهلي',
    'Al Ahly': 'الأهلي',
    'Zamalek (EGY)': 'الزمالك',
    'Zamalek': 'الزمالك',
    'Al Ain (UAE)': 'العين',
    'Al Ain': 'العين',
    'Al Sadd (QAT)': 'السد',
    'Al Sadd': 'السد',
    'Raja Casablanca (MAR)': 'الرجاء',
    'Raja Casablanca': 'الرجاء',
    'Wydad Casablanca (MAR)': 'الوداد',
    'Wydad Casablanca': 'الوداد',
    'Espérance de Tunis (TUN)': 'الترجي',
    'Espérance de Tunis': 'الترجي',
    'Club Africain (TUN)': 'النادي الإفريقي',
    'Club Africain': 'النادي الإفريقي',
    'Al Ittihad (KSA)': 'الاتحاد',
    'Al Ittihad': 'الاتحاد',
    'Al Shabab (KSA)': 'الشباب',
    'Al Shabab': 'الشباب',
    'Al Wahda (UAE)': 'الوحدة',
    'Al Wahda': 'الوحدة',
    'Al Wasl (UAE)': 'الوصل',
    'Al Wasl': 'الوصل',
    'Al Jazira (UAE)': 'الجزيرة',
    'Al Jazira': 'الجزيرة',
    'Al Rayyan (QAT)': 'الريان',
    'Al Rayyan': 'الريان',
    'Al Duhail (QAT)': 'الدحيل',
    'Al Duhail': 'الدحيل',
    'Al Gharafa (QAT)': 'الغرافة',
    'Al Gharafa': 'الغرافة',
    'Al Wakrah (QAT)': 'الوكرة',
    'Al Wakrah': 'الوكرة',
    'Al Khor (QAT)': 'الخور',
    'Al Khor': 'الخور',
    'Al Sailiya (QAT)': 'السيلية',
    'Al Sailiya': 'السيلية',
    'Al Markhiya (QAT)': 'المرخية',
    'Al Markhiya': 'المرخية',
    'Al Shamal (QAT)': 'الشمال',
    'Al Shamal': 'الشمال',
    'Al Fateh (KSA)': 'الفتح',
    'Al Fateh': 'الفتح',
    'Al Taawoun (KSA)': 'التعاون',
    'Al Taawoun': 'التعاون',
    'Al Faisaly (KSA)': 'الفيصلي',
    'Al Faisaly': 'الفيصلي',
    'Al Raed (KSA)': 'الرائد',
    'Al Raed': 'الرائد',
    'Al Batin (KSA)': 'الباطن',
    'Al Batin': 'الباطن',
    'Al Adalah (KSA)': 'العدالة',
    'Al Adalah': 'العدالة',
    'Al Hazm (KSA)': 'الحزم',
    'Al Hazm': 'الحزم',
    'Al Okhdood (KSA)': 'الأخدود',
    'Al Okhdood': 'الأخدود',
    'Al Riyadh (KSA)': 'الرياض',
    'Al Riyadh': 'الرياض',
    'Al Ettifaq (KSA)': 'الاتفاق',
    'Al Ettifaq': 'الاتفاق',
    'Al Khaleej (KSA)': 'الخليج',
    'Al Khaleej': 'الخليج',

   
   
  

    // Dutch Eredivisie
    'Ajax': 'أياكس',
    'PSV Eindhoven': 'بي إس في آيندهوفن',
    'Feyenoord': 'فاينورد',
    'AZ Alkmaar': 'إيه زد ألكمار',
    'FC Twente': 'تفينتي',
    'SC Heerenveen': 'هيرنفين',
    'Vitesse': 'فيتيس',
    'FC Utrecht': 'أوترخت',
    'Sparta Rotterdam': 'سبارتا روتردام',
    'Heracles': 'هيراكليس',

    // Portuguese Primeira Liga
    'Benfica': 'بنفيكا',
    'Porto': 'بورتو',
    'Sporting CP': 'سبورتنج لشبونة',
    'Braga': 'براغا',
    'Vitória Guimarães': 'فيتوريا غيمارايش',
    'Moreirense': 'موريرينسي',
    'Farense': 'فارينسي',
    'Estoril': 'إشتوريل',
    'Casa Pia': 'كاسا بيا',
    'Arouca': 'أروكا',

    // Belgian Pro League
    'Club Brugge': 'كلوب بروج',
    'Anderlecht': 'أندرلخت',
    'Standard Liège': 'ستاندارد لييج',
    'Genk': 'غينك',
    'Gent': 'غنت',
    'Antwerp': 'أنتويرب',
    'Charleroi': 'شارلروا',
    'Mechelen': 'ميشيلين',
    'Cercle Brugge': 'سيركل بروج',
    'Sint-Truiden': 'سانت ترويدن',

    // Turkish Süper Lig
    'Galatasaray': 'غلطة سراي',
    'Fenerbahçe': 'فنربخشة',
    'Beşiktaş': 'بشكتاش',
    'Trabzonspor': 'طرابزون سبور',
    'Adana Demirspor': 'أضنة دميرسبور',
    'Antalyaspor': 'أنطاليا سبور',
    'Konyaspor': 'قونية سبور',
    'Kayserispor': 'قيصري سبور',
    'Sivasspor': 'سيواس سبور',
    'Alanyaspor': 'ألانيا سبور',

    // Russian Premier League
    'Zenit Saint Petersburg': 'زينيت سانت بطرسبرغ',
    'Spartak Moscow': 'سبارتاك موسكو',
    'CSKA Moscow': 'سي إس كا موسكو',
    'Lokomotiv Moscow': 'لوكوموتيف موسكو',
    'Dynamo Moscow': 'دينامو موسكو',
    'Krasnodar': 'كراسنودار',
    'Rostov': 'روستوف',
    'Sochi': 'سوتشي',
    'Akhmat Grozny': 'أخمات غروزني',
    'Ural': 'أورال',

    // Ukrainian Premier League
    'Shakhtar Donetsk': 'شاختار دونيتسك',
    'Dynamo Kyiv': 'دينامو كييف',
    'Dnipro-1': 'دنبرو-1',
    'Vorskla Poltava': 'فورسكلا بولتافا',
    'Kolos Kovalivka': 'كولوس كوفاليفكا',
    'Rukh Lviv': 'روخ لفيف',
    'Metalist 1925': 'ميتاليست 1925',
    'Kryvbas Kryvyi Rih': 'كريفباس كريفي ريه',
    'LNZ Cherkasy': 'إل إن زد تشيركاسي',
    'Mynai': 'ميناي',

    // Polish Ekstraklasa
    'Legia Warsaw': 'ليجيا وارسو',
    'Lech Poznań': 'ليخ بوزنان',
    'Wisła Kraków': 'فيسلا كراكوف',
    'Górnik Zabrze': 'غورنيك زابجه',
    'Ruch Chorzów': 'روخ خورزوف',
    'Zagłębie Lubin': 'زاغلومبي لوبين',
    'Śląsk Wrocław': 'شلونسك فروتسواف',
    'Jagiellonia Białystok': 'ياغيلونيا بياويستوك',
    'Pogoń Szczecin': 'بوجون شتشيتسين',
    'Raków Częstochowa': 'راكوف تشيستوخوفا',

    // Austrian Bundesliga
    'Red Bull Salzburg': 'ريد بول سالزبورغ',
    'Rapid Vienna': 'رابيد فيينا',
    'Austria Vienna': 'أوستريا فيينا',
    'Sturm Graz': 'شتورم غراتس',
    'LASK': 'لاسك',
    'Wolfsberger AC': 'فولفسبرغر إيه سي',
    'Hartberg': 'هارتبرغ',
    'WSG Tirol': 'دبليو إس جي تيرول',
    'Austria Klagenfurt': 'أوستريا كلاغنفورت',
    'Blau-Weiß Linz': 'بلو-وايس لينز',

    // Swiss Super League
    'Young Boys': 'يونغ بويز',
    'Basel': 'بازل',
    'Zürich': 'زيورخ',
    'Lugano': 'لوغانو',
    'St. Gallen': 'سانت غالن',
    'Servette': 'سيرفيت',
    'Lausanne-Sport': 'لوزان-سبورت',
    'Winterthur': 'فينترتور',
    'Yverdon-Sport': 'إيفردون-سبورت',
    'Luzern': 'لوزيرن',

    // Scandinavian Leagues
    // Danish Superliga
    'Copenhagen': 'كوبنهاغن',
    'Brøndby': 'بروندبي',
    'Midtjylland': 'ميتجيولاند',
    'Aarhus': 'آرهوس',
    'Viborg': 'فيبورغ',
    'Silkeborg': 'سيلكيبرغ',
    'Nordsjælland': 'نوردسيلاند',
    'Randers': 'رانديرس',
    'Horsens': 'هورسينس',
    'Vejle': 'فايله',

    // Norwegian Eliteserien
    'Bodø/Glimt': 'بودو/غليمت',
    'Molde': 'مولده',
    'Rosenborg': 'روزنبورغ',
    'Vålerenga': 'فوليرينغا',
    'Lillestrøm': 'ليلستروم',
    'Strømsgodset': 'سترمسغودست',
    'Viking': 'فايكينغ',
    'Brann': 'بران',
    'Tromsø': 'ترومسو',
    'Odd': 'أود',

    // Swedish Allsvenskan
    'Malmö FF': 'مالمو إف إف',
    'AIK': 'أي آي كي',
    'Hammarby': 'هاماربي',
    'Djurgården': 'يورغوردن',
    'Häcken': 'هاكن',
    'Kalmar': 'كالمار',
    'Elfsborg': 'إلفسبورغ',
    'Norrköping': 'نورشوبينغ',
    'Örebro': 'أوربرو',
    'Östersund': 'أوسترسوند',

    // South American Clubs
    // Brazilian Serie A
    'Flamengo': 'فلامنغو',
    'Palmeiras': 'بالميراس',
    'Santos': 'سانتوس',
    'Corinthians': 'كورينثيانز',
    'São Paulo': 'ساو باولو',
    'Grêmio': 'غريميو',
    'Internacional': 'إنترناسيونال',
    'Vasco da Gama': 'فاسكو دا غاما',
    'Fluminense': 'فلومينينسي',
    'Atlético Mineiro': 'أتلتيكو مينيرو',
    'Cruzeiro': 'كروزيرو',
    'Botafogo': 'بوتافوغو',
    'Athletico Paranaense': 'أتلتيكو باراناينسي',
    'Fortaleza': 'فورتاليزا',
    'Bahia': 'باهيا',
    'Sport Recife': 'سبورت ريسيفي',
    'Vitória': 'فيتوريا',
    'Ceará': 'سيارا',
    'Chapecoense': 'شابيكوينسي',
    'Goiás': 'غوياس',

    // Argentine Primera División
    'Boca Juniors': 'بوكا جونيورز',
    'River Plate': 'ريفر بليت',
    'Racing Club': 'راسينغ كلوب',
    'Independiente': 'إنديبندينتي',
    'San Lorenzo': 'سان لورينزو',
    'Vélez Sarsfield': 'فيليز سارسفيلد',
    'Estudiantes': 'إستوديانتس',
    'Newell\'s Old Boys': 'نيويلز أولد بويز',
    'Rosario Central': 'روزاريو سنترال',
    'Gimnasia La Plata': 'خيمناسيا لا بلاتا',
    'Lanús': 'لانوس',
    'Banfield': 'بانفيلد',
    'Talleres': 'تاليريس',
    'Defensa y Justicia': 'ديفينسا إي خوستيسيا',
    'Argentinos Juniors': 'أرجنتينوس جونيورز',
    'Huracán': 'هوراكان',
    'Unión': 'يونيون',
    'Colón': 'كولون',

    'Patronato': 'باتروناتو',

    // Colombian Primera A
    'Atlético Nacional': 'أتلتيكو ناسيونال',
    'Millonarios': 'ميلوناريوس',
    'América de Cali': 'أمريكا دي كالي',
    'Deportivo Cali': 'ديبورتيفو كالي',
    'Junior': 'خونيور',
    'Once Caldas': 'أونس كالداس',
    'Independiente Medellín': 'إنديبندينتي ميديلين',
    'Envigado': 'إينفيغادو',
    'Deportes Tolima': 'ديبورتيس توليما',
    'Santa Fe': 'سانتا في',
    'La Equidad': 'لا إكيداد',
    'Águilas Doradas': 'أغيلاس دوراداس',
    'Jaguares de Córdoba': 'جاغواريس دي كوردوبا',
    'Alianza Petrolera': 'أليانزا بتروليرا',
    'Patriotas': 'باتريوتاس',
    'Cortuluá': 'كورتولوا',

    'Boyacá Chicó': 'بوياكا تشيكو',
    'Unión Magdalena': 'يونيون ماجدالينا',
    'Real Cartagena': 'ريال كارتاخينا',

    // Chilean Primera División
    'Colo-Colo': 'كولو-كولو',
    'Universidad de Chile': 'أونيفرسيداد دي تشيلي',
    'Universidad Católica': 'أونيفرسيداد كاتوليكا',
    'Palestino': 'فلسطينو',
    'Unión Española': 'يونيون إسبانيولا',
    'Audax Italiano': 'أوداكس إيطاليانو',
    'O\'Higgins': 'أوهيغينز',
    'Unión La Calera': 'يونيون لا كاليرا',
    'Deportes Antofagasta': 'ديبورتيس أنتوفاغاستا',
    'Cobresal': 'كوبريسال',
    'Huachipato': 'هواتشيباتو',
    'Deportes Iquique': 'ديبورتيس إيكيكي',
    'Santiago Wanderers': 'سانتياغو واندررز',
    'Deportes La Serena': 'ديبورتيس لا سيرينا',
    'Ñublense': 'نيوبلينسي',
    'Coquimbo Unido': 'كوكيمبو أونيدو',
    'Deportes Copiapó': 'ديبورتيس كوبيابو',
    'Deportes Temuco': 'ديبورتيس تيموكو',
    'Rangers': 'رينجرز',

    // Peruvian Primera División
    'Universitario': 'أونيفرسيتاريو',
    'Alianza Lima': 'أليانزا ليما',
    'Sporting Cristal': 'سبورتينغ كريستال',
    'Melgar': 'ميلغار',
    'Cienciano': 'سيينسيانو',
    'Sport Boys': 'سبورت بويز',
    'Deportivo Municipal': 'ديبورتيفو مونيسيبال',
    'Universitario de Deportes': 'أونيفرسيتاريو دي ديبورتس',
    'FBC Melgar': 'إف بي سي ميلغار',
    'Alianza Atlético': 'أليانزا أتلتيكو',
    'Cusco FC': 'كوسكو إف سي',
    'Ayacucho FC': 'أياكوتشو إف سي',
    'Carlos A. Mannucci': 'كارلوس إيه مانوتشي',
    'Deportivo Garcilaso': 'ديبورتيفو غارسيلاسو',
    'Unión Comercio': 'يونيون كوميرسيو',
    'Academia Cantolao': 'أكاديميا كانتولاو',
    'ADT': 'إيه دي تي',
    'UTC': 'يو تي سي',
    'Deportivo Binacional': 'ديبورتيفو بيناسيونال',

    // Uruguayan Primera División
    'Peñarol': 'بينارول',
    'Nacional': 'ناسيونال',
    'Defensor Sporting': 'ديفينسور سبورتينغ',
    'Danubio': 'دانوبيو',
 
    'Cerro': 'سيرو',
    'Wanderers': 'واندررز',
    'Progreso': 'بروغريسو',
    'Fénix': 'فينيكس',
    'Rentistas': 'رينتستاس',
    'Plaza Colonia': 'بلازا كولونيا',
    'Boston River': 'بوسطن ريفر',
    'Cerro Largo': 'سيرو لارغو',
   
    'Villa Española': 'فيلا إسبانيولا',
    'Deportivo Maldonado': 'ديبورتيفو مالدونادو',
    'Albion': 'ألبايون',
    'La Luz': 'لا لوز',
    'Atenas': 'أثيناس',
    'Miramar Misiones': 'ميرامار ميسيونس',

    // African Clubs
    // Egyptian Premier League
   
    'Pyramids': 'الأهرام',
    'Future': 'المستقبل',
    'Ceramica Cleopatra': 'سيراميكا كليوباترا',
    'ENPPI': 'إينبي',
    'Ismaily': 'الإسماعيلي',
    'Smouha': 'سموحة',
    'El Gouna': 'الجونة',
    'Tala\'ea El Gaish': 'طلائع الجيش',
    'El Masry': 'المصري',
    'Aswan': 'أسوان',
    'El Daklyeh': 'الداخلية',
    'El Geish': 'الجيش',
    'El Mokawloon': 'المقاولون',
    'El Sharkia': 'الشرقية',
    'El Wadi Degla': 'وادي دجلة',
    'Haras El Hodoud': 'حرس الحدود',
    'Misr Lel Makkasa': 'مصر للمقاصة',
    'Nogoom': 'نجوم',

    // Moroccan Botola

    'FAR Rabat': 'القوات المسلحة الملكية',
    'FUS Rabat': 'اتحاد سلا',
    'Ittihad Tanger': 'اتحاد طنجة',
    'RS Berkane': 'اتحاد بركان',
    'Olympic Khouribga': 'أولمبيك خريبكة',
    'Olympic Safi': 'أولمبيك آسفي',
    'Ittihad Khemisset': 'اتحاد الخميسات',
    'Union Touarga': 'اتحاد تواركة',
    'Youssoufia Berrechid': 'يوسفية برشيد',
    'Renaissance Zemamra': 'نهضة زمامرة',
    'Union Sidi Kacem': 'اتحاد سيدي قاسم',
    'Olympic Tetouan': 'أولمبيك تطوان',
    'Renaissance Berkane': 'نهضة بركان',
    'Maghreb de Fès': 'المغرب الفاسي',
    'Renaissance Salé': 'نهضة سلا',
    'Union Aït Melloul': 'اتحاد آيت ملول',
    'Renaissance Tétouan': 'نهضة تطوان',
    'Union Sidi Slimane': 'اتحاد سيدي سليمان',

    // Tunisian Ligue 1
 
    'Étoile du Sahel': 'النجمة',
    'CS Sfaxien': 'النادي الصفاقسي',
    'US Monastir': 'الاتحاد المنستيري',
    'CA Bizertin': 'النادي البنزرتي',
    'Stade Tunisien': 'الملعب التونسي',
    'AS Marsa': 'النجم الرياضي المرسي',
    'JS Kairouan': 'الجمعية الرياضية للقيروان',
    'US Tataouine': 'الاتحاد التطاوني',
    'AS Gabès': 'النجم الرياضي للقابس',
    'CS Hammam-Lif': 'النادي الرياضي لحمام الأنف',
    'JS Soualem': 'الجمعية الرياضية للسوالم',
    'AS Soliman': 'النجم الرياضي لسليمان',
    'US Ben Guerdane': 'الاتحاد البنقرداني',
    'AS Rejiche': 'النجم الرياضي للرجيش',
    'ES Métlaoui': 'النجم الرياضي للمتلوي',
    'US Siliana': 'الاتحاد السلياني',
    'AS Djerba': 'النجم الرياضي لجربة',
    'JS Tabarka': 'الجمعية الرياضية لطبرقة',

    // Algerian Ligue 1
    'CR Belouizdad': 'شباب بلوزداد',
    'JS Kabylie': 'شباب القبائل',
    'MC Alger': 'مولودية الجزائر',
    'ES Sétif': 'نجم سطيف',
    'USM Alger': 'اتحاد العاصمة',
    'MC Oran': 'مولودية وهران',
    'JS Saoura': 'شباب الساورة',
    'NA Hussein Dey': 'نصر حسين داي',
    'USM Bel Abbès': 'اتحاد بلعباس',
    'Paradou AC': 'بارادو إيه سي',
    'RC Arbaâ': 'رائد القبة',
    'ASO Chlef': 'أولمبيك الشلف',
    'US Biskra': 'اتحاد بسكرة',
    'RC Relizane': 'رائد غليزان',
    'JSM Skikda': 'شباب سكيكدة',
    'USM Annaba': 'اتحاد عنابة',
    'MO Béjaïa': 'مولودية بجاية',
    'AS Ain M\'lila': 'نجم عين مليلة',
    'USM El Harrach': 'اتحاد الحراش',
    'NC Magra': 'نصر مقرة',

    // Asian Clubs
    // Chinese Super League
    'Guangzhou Evergrande': 'غوانغتشو إيفرغراند',
    'Shanghai SIPG': 'شانغهاي إس آي بي جي',
    'Beijing Guoan': 'بكين غوان',
    'Shandong Taishan': 'شاندونغ تايشان',
    'Jiangsu Suning': 'جيانغسو سونينغ',
    'Shanghai Shenhua': 'شانغهاي شينهوا',
    'Tianjin TEDA': 'تيانجين تيدا',
    'Dalian Pro': 'داليان برو',
    'Henan Songshan Longmen': 'خنان سونغشان لونغمين',
    'Chongqing Liangjiang Athletic': 'تشونغتشينغ ليانغجيانغ أتلتيك',
    'Hebei': 'خبي',
    'Guangzhou City': 'غوانغتشو سيتي',
    'Shenzhen': 'شنتشن',
    'Wuhan Three Towns': 'ووهان ثري تاونز',
    'Chengdu Rongcheng': 'تشنغدو رونغتشنغ',
    'Zhejiang': 'تشجيانغ',
    'Meizhou Hakka': 'ميتشو هاكا',
    'Nantong Zhiyun': 'نانتونغ زهيون',
    'Qingdao Hainiu': 'تشينغداو هاينيو',
    'Dalian Yifang': 'داليان ييفانغ',

    // South Korean K League 1
    'Ulsan Hyundai': 'أولسان هيونداي',
    'Jeonbuk Hyundai Motors': 'جونبوك هيونداي موتورز',
    'Pohang Steelers': 'بوهانغ ستيلرز',
    'Suwon Samsung Bluewings': 'سوون سامسونغ بلووينغز',
    'FC Seoul': 'إف سي سيول',
    'Jeju United': 'جيجو يونايتد',
    'Daegu FC': 'دايجو إف سي',
    'Gangwon FC': 'غانغوون إف سي',
    'Suwon FC': 'سوون إف سي',
    'Incheon United': 'إنتشون يونايتد',
    'Gwangju FC': 'غوانغجو إف سي',
    'Daejeon Hana Citizen': 'دايجون هانا سيتيزن',
    'Seongnam FC': 'سونغنام إف سي',
    'Busan IPark': 'بوسان آي بارك',
    'Gimcheon Sangmu': 'غيمتشون سانغمو',
    'Jeonnam Dragons': 'جيونام دراغونز',
    'Ansan Greeners': 'أنسان غرينرز',
    'Bucheon FC 1995': 'بوتشون إف سي 1995',
    'Anyang FC': 'أنيانغ إف سي',
    'Gyeongnam FC': 'غيونغنام إف سي',

    // Australian A-League
    'Melbourne City': 'ملبورن سيتي',
    'Sydney FC': 'سيدني إف سي',
    'Adelaide United': 'أديلايد يونايتد',
    'Brisbane Roar': 'بريزبن رور',
    'Perth Glory': 'بيرث غلوري',
    'Western Sydney Wanderers': 'ويسترن سيدني واندررز',
    'Newcastle Jets': 'نيوكاسل جيتس',
    'Wellington Phoenix': 'ويلينغتون فينيكس',
    'Central Coast Mariners': 'سينترال كوست مارينرز',
    'Macarthur FC': 'ماك آرثر إف سي',
    'Melbourne Victory': 'ملبورن فيكتوري',
    'Western United': 'ويسترن يونايتد',

    // Indian Super League
    'Mumbai City': 'مومباي سيتي',
    'ATK Mohun Bagan': 'إيه تي كي موهون باغان',
    'Bengaluru FC': 'بنغالورو إف سي',
    'Chennaiyin FC': 'تشينايين إف سي',
    'FC Goa': 'إف سي غوا',
    'Hyderabad FC': 'حيدر أباد إف سي',
    'Jamshedpur FC': 'جمشيدبور إف سي',
    'Kerala Blasters': 'كيرالا بلاسترز',
    'NorthEast United': 'نورث إيست يونايتد',
    'Odisha FC': 'أوديشا إف سي',
    'Punjab FC': 'بنجاب إف سي',
    'East Bengal': 'إيست بنغال',

    // North American Clubs
    // MLS (Major League Soccer)
    'LA Galaxy': 'إل إيه غالاكسي',
    'LAFC': 'إل إيه إف سي',
    'Seattle Sounders': 'سياتل ساوندرز',
    'Portland Timbers': 'بورتلاند تيمبرز',
    'Vancouver Whitecaps': 'فانكوفر وايتكابس',
    'San Jose Earthquakes': 'سان خوسيه إيرثكويكس',
    'Real Salt Lake': 'ريال سولت ليك',
    'Colorado Rapids': 'كولورادو رابيدز',
    'FC Dallas': 'إف سي دالاس',
    'Houston Dynamo': 'هيوستن دينامو',
    'Sporting Kansas City': 'سبورتينغ كانساس سيتي',
    'Minnesota United': 'مينيسوتا يونايتد',
    'Chicago Fire': 'شيكاغو فاير',
    'Columbus Crew': 'كولومبوس كرو',
    'FC Cincinnati': 'إف سي سينسيناتي',
    'New York City FC': 'نيويورك سيتي إف سي',
    'New York Red Bulls': 'نيويورك ريد بولز',
    'Philadelphia Union': 'فيلادلفيا يونيون',
    'DC United': 'دي سي يونايتد',
    'New England Revolution': 'نيو إنجلاند ريفولوشن',
    'Toronto FC': 'تورونتو إف سي',
    'Montreal Impact': 'مونتريال إمباكت',
    'Atlanta United': 'أتلانتا يونايتد',
    'Orlando City': 'أورلاندو سيتي',
    'Inter Miami': 'إنتر ميامي',
    'Nashville SC': 'ناشفيل إس سي',
    'Austin FC': 'أوستن إف سي',
    'Charlotte FC': 'شارلوت إف سي',
    'St. Louis City SC': 'سانت لويس سيتي إس سي',

    // Mexican Liga MX
    'Club América': 'كلوب أمريكا',
    'Guadalajara': 'غوادالاخارا',
    'Cruz Azul': 'كروز أزول',
    'UNAM': 'أونام',
    'Tigres UANL': 'تيغريس أونال',
    'Monterrey': 'مونتيري',
    'Santos Laguna': 'سانتوس لاغونا',
    'Tijuana': 'تيخوانا',
    'Pachuca': 'باتشوكا',
    'Toluca': 'تولوكا',
    'Puebla': 'بويبلا',
    'Querétaro': 'كيريتارو',
    'Atlas': 'أطلس',
    'León': 'ليون',
    'Necaxa': 'نيكاكسا',
    'Mazatlán': 'مازاتلان',
    'Juárez': 'خواريز',
    'San Luis': 'سان لويس',
    'Atlético San Luis': 'أتلتيكو سان لويس',


    // Oceania Clubs
    'Auckland City': 'أوكلاند سيتي',
  
  };

  // Error messages in Arabic
  static const Map<String, String> errorMessages = {
    'api_error': 'حدث خطأ في الاتصال بالخادم. يرجى المحاولة مرة أخرى.',
    'network_error':
        'لا يوجد اتصال بالإنترنت. يرجى التحقق من اتصالك والمحاولة مرة أخرى.',
    'rate_limit': 'تم تجاوز حد الطلبات المسموح به. يرجى المحاولة بعد قليل.',
    'invalid_api_key':
        'مفتاح API غير صالح. يرجى التحقق من المفتاح وإعادة المحاولة.',
    'not_found': 'لم يتم العثور على البيانات المطلوبة.',
    'no_data': 'لا توجد بيانات متاحة في الوقت الحالي.',
    'server_error': 'خطأ في الخادم. يرجى المحاولة لاحقاً.',
    'timeout_error': 'انتهت مهلة الاتصال. يرجى المحاولة مرة أخرى.',
    'unauthorized': 'غير مصرح بالوصول. يرجى التحقق من صلاحياتك.',
    'forbidden': 'ممنوع الوصول. يرجى التحقق من إعداداتك.',
  };

  // Match status translations in Arabic
  static const Map<String, String> matchStatusArabic = {
    // Basic statuses
    'FT': 'انتهت',
    'NS': 'لم تبدأ',
    '1H': 'الشوط الأول',
    '2H': 'الشوط الثاني',
    'HT': 'استراحة',
    'P': 'مؤجل',
    'C': 'ملغي',
    'AET': 'انتهت بعد الأشواط الإضافية',
    'PEN': 'انتهت بركلات الترجيح',
    'BT': 'استراحة',
    'SUSP': 'معلق',
    'INT': 'معلق',
    'PST': 'مؤجل',
    'CANC': 'ملغي',
    'ABD': 'معلق',
    'AWD': 'فوز تلقائي',
    'WO': 'انسحاب',
    'LIVE': 'جارية',
    'PEN_LIVE': 'ركلات الترجيح',
    'BREAK': 'استراحة',
    'FT_PEN': 'انتهت بركلات الترجيح',
    'AWAITING_UPDATES': 'في انتظار التحديثات',
    'DELAYED': 'متأخرة',
    'TBD': 'لم يتم تحديدها',
    'POSTPONED': 'مؤجلة',
    'CANCELLED': 'ملغية',
    'SUSPENDED': 'معلقة',
    'INTERRUPTED': 'معلقة',
    'ABANDONED': 'معلقة',
    'TECHNICAL_LOSS': 'خسارة تقنية',
    'WALKOVER': 'انسحاب',
    'AWARDED': 'ممنوحة',

    // Additional statuses
    'ET': 'أشواط إضافية',

    'HALF_TIME': 'استراحة',
    'FULL_TIME': 'انتهت',
    'NOT_STARTED': 'لم تبدأ',
  };

  // App theme colors
  static const Map<String, int> themeColors = {
    'primary': 0xFF295CD2, // Blue
    'secondary': 0xFF4CAF50, // Green
    'accent': 0xFFFF9800, // Orange
    'error': 0xFFF44336, // Red
    'warning': 0xFFFFEB3B, // Yellow
    'success': 0xFF4CAF50, // Green
    'info': 0xFF2196F3, // Blue
    'light': 0xFFF5F5F5, // Light Grey
    'dark': 0xFF212121, // Dark Grey
    'white': 0xFFFFFFFF, // White
    'black': 0xFF000000, // Black
  };

  // App settings
  static const Map<String, dynamic> appSettings = {
    'refresh_interval': 30000, // 30 seconds
    'max_retries': 3,
    'timeout_duration': 10000, // 10 seconds
    'cache_duration': 300000, // 5 minutes
    'max_matches_per_page': 50,
    'enable_notifications': true,
    'enable_sound': true,
    'enable_vibration': true,
    'language': 'ar',
    'theme': 'auto',
  };
}
